language: c
sudo: false

matrix:
  include:
    - env: TASK="osx"
      os: osx
      compiler: clang
      before_install: rvm get stable
      install:
        - brew update
        - brew install python3 ninja pkg-config pcre2 portaudio; echo "done"
        - pip3 install meson
    - env: TASK="ios"
      os: osx
      compiler: clang
      before_install: rvm get stable
      install:
        - brew update
        - brew install python3 ninja pkg-config; echo "done"
        - pip3 install meson
      script:
        - meson build --prefix="$PWD/install" --cross-file="subprojects/mimic-core/cross/iphone.txt"
        - ninja -C build install
    - env: TASK="linux"
      os: linux
      dist: "trusty"
      install:
        - export PATH="`pwd`/build:${PATH}"
        - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        - pip3 install meson
      addons: {apt: {packages: [libasound2-dev, python3-pip, pkg-config]}}
    - env: TASK="coverage"
      os: linux
      dist: "trusty"
      install:
        - export PATH="`pwd`/build:${PATH}"
        - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        - pip3 install meson
      script:
        - meson build --prefix="$PWD/install" -D b_coverage=true
        - ninja -C build test install
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      addons: {apt: {packages: [libasound2-dev, python3-pip, pkg-config]}}
    - env: TASK="windows"
      os: linux
      dist: "trusty"
      install:
        - export PATH="`pwd`/build:${PATH}"
        - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        - pip3 install meson
      script:
        - meson build --prefix="$PWD/install" --cross-file="subprojects/mimic-core/cross/ubuntu-mingw64.txt"
        - ninja -C build install
      addons: {apt: {packages: [python3-pip, pkg-config, wine, binutils-mingw-w64-x86-64, mingw-w64-x86-64-dev, gcc-mingw-w64-x86-64]}}
    - env: TASK="armhf"
      os: linux
      dist: "trusty"
      install:
        - export PATH="`pwd`/build:${PATH}"
        - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
        - pip3 install meson
      script:
        - meson build --prefix="$PWD/install" --cross-file="subprojects/mimic-core/cross/ubuntu-armhf.txt"
        - ninja -C build install
      addons: {apt: {packages: [python3-pip, pkg-config-arm-linux-gnueabihf, libc6-dev-armhf-cross, gcc-arm-linux-gnueabihf, binutils-arm-linux-gnueabihf]}}

# We don't want to pull submodules recursively
git:
  submodules: false

before_install:
  - git submodule update --init

script:
  - meson build --prefix="$PWD/install"
  - ninja -C build test install

